import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // points to website/docs/intro.md
      label: 'Book Overview',
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1 Overview',
        slug: '/module1',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        title: 'Module 2 Overview',
        slug: '/module2',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {
        type: 'generated-index',
        title: 'Module 3 Overview',
        slug: '/module3',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {
        type: 'generated-index',
        title: 'Module 4 Overview',
        slug: '/module4',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4',
        },
      ],
    },
  ],
};

export default sidebars;