import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1 Overview',
        slug: '/module1',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1',
        },
      ],
    },
  ],
};

export default sidebars;